name: Auto Merge PR from Specific Users

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Setting up GitHub CLI"

      - name: Check if PR is from a specific user
        id: check_user
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_author=$(jq -r .pull_request.user.login "$GITHUB_EVENT_PATH")
          echo "PR Author: $pr_author"
          if [[ "$pr_author" != "andrei-vig" && "$pr_author" != "hithaprani" ]]; then
            echo "PR is not from a specified user."
            exit 1
          fi

      - name: Check that only devices.json is in the PR
        id: check_files
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          changed_files=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')
          if [[ "$changed_files" != "devices.json" ]]; then
            echo "PR contains files other than 'devices.json'."
            exit 1
          fi

      - name: Validate JSON structure
        id: validate_json
        run: |
          python scripts/validate_devices_json.py devices.json
        continue-on-error: true

      - name: Request changes if validation failed
        if: steps.validate_json.outcome == 'failure'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "The JSON file doesn't follow the required structure. Please correct the issues and resubmit."
          exit 1

      - name: Auto-merge the pull request
        if: steps.validate_json.outcome == 'success'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --auto --merge
